### ISSUE TITLE
Kotlin Tests not working

### ISSUE THREAD

**Issue by objectbay-florian-bammer** [codurance/task-list#18]
Hello,

after checking this repo out and trying to start the kotlin tests you receive the following message:
> Kotlin: Language version 1.1 is no longer supported; please, use version 1.3 or greater.

**Comment by SamirTalwar** [comment]
Not surprising! Could you try out #17 and see if it solves your problem? If so, we can merge it.

**Comment by objectbay-florian-bammer** [comment]
Thanks for the fast response - yes its working! :slightly_smiling_face:
